### ISSUE TITLE
Where are email and password stored?

### ISSUE THREAD

**Issue by tjluoma** [Andrew-Morozko/cloudy-uploader#3]
The README mentions that they are stored in plain text. I assumed it would be in some ~/.hiddenfile but I didn't find anything after running it, so I'm curious where it ended up.

**Comment by tjluoma** [comment]
Answer: **"$HOME/Library/Application Support/cloudyuploader/config.json"**

It would certainly be preferable to store these in the macOS Keychain rather than in a file on the disk, but it's not enough to keep me from using an otherwise useful tool.

**Comment by Andrew-Morozko** [comment]
Yep, keychain would've been the better choice, but for some reason I was sure It would be hard to support it in Go. Turns out there are a bunch of libraries for it, derp;) 

I'll add keychain support in the next version.

**Comment by Andrew-Morozko** [comment]
Finally got around to addressing this. In the latest release the credentials are now stored in the keychain.
